apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: '${Cluster1Name}'
  region: '${AWS_REGION}'
  version: '1.28'
  tags:
    EnvironmentName: '${EnvironmentName}'

vpc:
  subnets: 
    private:
      private1:
          id: '${PrivateSubnet1}'
      private2:
          id: '${PrivateSubnet2}'
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
- name: ng
  desiredCapacity: 2
  instanceType: t3.medium
  privateNetworking: true
  subnets: 
    - private1
    - private2
