apiVersion: v1
kind: ConfigMap
metadata:
  name: module1-configmap
data:
  index.html: |
    <html>
      <head>
        <title> Welcome to Amazon EKS </title>
      </head>
      <body>
        <h1> You are accessing the application in cluster1 </h1>
        <h3> Knowledge is valuable only when it is shared. </h3>
      </body>
    </html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module1
  template:
    metadata:
      labels:
        app: module1
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        volumeMounts:
          - name: indexpage
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: indexpage
        projected:
          sources:
            - configMap:
                name: module1-configmap
--- 
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: module1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
